name: hello-github-actions
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "Hello Github Actions !"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "Hello second-job !"